//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberarms.IntrusionDetection.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberarms.IntrusionDetection.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_custom_dark {
            get {
                object obj = ResourceManager.GetObject("agent15px_custom_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_custom_white {
            get {
                object obj = ResourceManager.GetObject("agent15px_custom_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_default_dark {
            get {
                object obj = ResourceManager.GetObject("agent15px_default_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_default_white {
            get {
                object obj = ResourceManager.GetObject("agent15px_default_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                     
        ///                                                    &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventsPerAgent {
            get {
                return ResourceManager.GetString("EventsPerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family:
        ///        &amp;quot;Helvetica&amp;quot;,&amp;quot;sans-serif&amp;quot;;mso-fareast-font-family:&amp;quot;Times New Roman [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HardLocksByIp {
            get {
                return ResourceManager.GetString("HardLocksByIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       
        ///                                                    &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family:
        ///        &amp;quot;Helvetica&amp;quot;,&amp;quot;sans-ser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntrusionAttemptsByIp {
            get {
                return ResourceManager.GetString("IntrusionAttemptsByIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_hardLock {
            get {
                object obj = ResourceManager.GetObject("logIcon_hardLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_loginAttempt {
            get {
                object obj = ResourceManager.GetObject("logIcon_loginAttempt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_softLock {
            get {
                object obj = ResourceManager.GetObject("logIcon_softLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_systemMessage {
            get {
                object obj = ResourceManager.GetObject("logIcon_systemMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_unlock {
            get {
                object obj = ResourceManager.GetObject("logIcon_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_warning {
            get {
                object obj = ResourceManager.GetObject("logIcon_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        
        ///        &lt;!-- Facebook sharing information tags --&gt;
        ///        &lt;meta property=&quot;og:title&quot; content=&quot;[%TITLE%]&quot; /&gt;
        ///        
        ///        &lt;title&gt;[%TITLE%]&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///
        /// p.MsoNormal
        ///  {margin-bottom:.0001pt;
        ///  font-size:12.0pt;
        ///  font-family:&quot;Times New Roman&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family:
        ///        &amp;quot;Helvetica&amp;quot;,&amp;quot;sans-serif&amp;quot;;mso-fareast-font-family:&amp;quot;Times New Roman&amp;quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoftLocksByIp {
            get {
                return ResourceManager.GetString("SoftLocksByIp", resourceCulture);
            }
        }
    }
}
